[package]
name = "aoc_3"
version = "0.1.0"
authors = ["Ian Hoffman <ijh6@cornell.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util" }